version: '3'

services:

  micro_email_php:
    container_name: micro_email_php
    build: ./docker/php
    volumes:
    - ./:/app
    ports:
    - '9000:9000'
    depends_on:
      micro_email_rabbitmq:
        condition: service_healthy
    command: sh -c "composer install --ignore-platform-reqs && php src/run.php"

  micro_email_nginx:
    image: nginx:alpine
    container_name: micro_email_nginx
    volumes:
    - ./:/app
    - ./docker/nginx/site.conf:/etc/nginx/conf.d/default.conf
    ports:
    - '8080:80'
    links:
    - micro_email_php

  micro_email_rabbitmq:
    image: "rabbitmq:3-management"
    container_name: micro_email_rabbitmq
    hostname: "rabbit"
    ports:
    - "15672:15672"
    - "5672:5672"
    labels:
      NAME: "rabbitmq"
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 30s
      timeout: 30s
      retries: 3
    volumes:
    - ./rabbitmq-isolated.conf:/etc/rabbitmq/rabbitmq.config

  micro_email_flask:
    build: ./flask
    container_name: micro_email_flask
    links:
    - micro_email_db
    - micro_email_rabbitmq
    ports:
    - "5000:5000"

  micro_email_db:
    image: mysql:5.7
    container_name: micro_email_db
    ports:
    - "32000:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
    - ./db:/docker-entrypoint-initdb.d/:ro
